baseURL = 'https://realspaceeagle.github.io/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
