baseURL = 'https://realspaceeagle.github.io/'
languageCode = 'en-us'
title = 'realspaceeagle - Cybersecurity Expert & Penetration Tester'
theme = 'PaperMod'

# SEO and Meta configuration
description = "Expert cybersecurity insights, penetration testing tutorials, and hands-on security demonstrations. Learn ethical hacking, network security, and defensive techniques with real-world scenarios."
keywords = ["cybersecurity", "penetration testing", "ethical hacking", "network security", "vulnerability assessment", "security tutorials", "infosec", "cyber defense"]
author = "realspaceeagle"

# Google Analytics configuration
googleAnalytics = "G-GPTRZ14YZS"

# Enable robots.txt generation
enableRobotsTXT = true

# Enable XML sitemap
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# Suppress raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShareButtons = ["x", "linkedin", "reddit", "telegram", "whatsapp", "email", "copy"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  search = true
  
  # Analytics settings
  env = "production"
  
  # SEO Settings
  description = "Expert cybersecurity insights, penetration testing tutorials, and hands-on security demonstrations. Learn ethical hacking, network security, and defensive techniques with real-world scenarios."
  keywords = ["cybersecurity", "penetration testing", "ethical hacking", "network security", "vulnerability assessment", "security tutorials", "infosec", "cyber defense", "hackthebox", "oscp", "malware analysis"]
  images = ["/images/og-image.svg"]
  
  # Open Graph / Twitter Card settings
  [params.opengraph]
  locale = "en_US"
  type = "website"
  site_name = "realspaceeagle - Cybersecurity Expert"
  
  [params.twitter]
  card = "summary_large_image"
  site = "@haran_loga"
  creator = "@haran_loga"

  # Favicon configuration
  [params.assets]
  favicon = "favicon.svg"
  favicon16x16 = "favicon.svg"
  favicon32x32 = "favicon.svg"
  apple_touch_icon = "favicon.svg"
  safari_pinned_tab = "favicon.svg"

  # Comment system configuration (Utterances)
  [params.utterances]
  repo = "realspaceeagle/realspaceeagle.github.io"
  issueTerm = "pathname"
  theme = "preferred-color-scheme"

  # Author configuration
  [params.author]
  name = "realspaceeagle"
  title = "Cybersecurity Professional & Penetration Tester"
  bio = "Cybersecurity enthusiast specializing in penetration testing, network security, and offensive security. Sharing knowledge through practical tutorials, tool reviews, and real-world scenarios. Passionate about helping others learn cybersecurity through hands-on experience."
  avatar = "/images/avatar.svg"

  # Newsletter configuration
  [params.newsletter]
  formspreeId = "xpzgkrdq"

  # Contact form configuration  
  [params.contact]
  formspreeId = "xpzgkrdq"

  # Social Media Icons
  [[params.socialIcons]]
  name = "linkedin"
  title = "Connect on LinkedIn"
  url = "https://www.linkedin.com/in/dream4ip/"

  [[params.socialIcons]]
  name = "x"
  title = "Follow on X/Twitter"
  url = "https://twitter.com/haran_loga"

  [[params.socialIcons]]
  name = "github"
  title = "View Code on GitHub"
  url = "https://github.com/realspaceeagle"

# Enable taxonomies for tags and categories
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Enable JSON output for search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

  [[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 30

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 50

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 55

  [[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 55

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 60

# Syntax highlighting configuration
[markup]
  [markup.highlight]
    style = "github-dark"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    tabWidth = 4
    anchorLineNos = false
    lineAnchors = ""
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Fuse.js search configuration
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

# Related posts configuration
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
