baseURL = 'https://realspaceeagle.github.io/'
languageCode = 'en-us'
title = 'realspaceeagle'
theme = 'PaperMod'

# Google Analytics configuration
googleAnalytics = "G-GPTRZ14YZS"

# Suppress raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  search = true
  
  # Analytics settings
  env = "production"

  # Social Media Icons
  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/dream4ip/"

  [[params.socialIcons]]
  name = "x"
  url = "https://twitter.com/haran_loga"

# Enable taxonomies for tags and categories
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Enable JSON output for search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

  [[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 30

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 50

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 55

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 60

# Syntax highlighting configuration
[markup]
  [markup.highlight]
    style = "github-dark"
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    tabWidth = 4
    anchorLineNos = false
    lineAnchors = ""
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Fuse.js search configuration
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
