baseURL = 'https://realspaceeagle.github.io/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

# Enable taxonomies for tags and categories
[taxonomies]
  category = "categories"
  tag = "tags"

# Enable JSON output for search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

  [[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 20

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 30

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 40

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 50

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 60

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  search = true

# Fuse.js search configuration
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
